### ISSUE TITLE
не работает хук с planfix

### ISSUE THREAD

**Issue by andruwa13** [popstas/server-scripts#1]
Здравствуйте, пытаюсь настроить так как у вас расписано в [статье](http://blog.popstas.ru/blog/2016/03/02/git-gitlab-planfix-integration/) но в планфикс так ничего и не приходит. Мы работаем с **gitlab** схема работа такая:

- у нас 98% сайтов это на Wordpress (2% на Joomla)
- есть дев версии сайтов и прод.
-  программисты работают локально, и заливают в репозиторий. По вебхуку правки автоматически заливаются на дев версии сайтов. Продакт Менеджер проверяет работу дев версий и заливает (merge) правки на прод

Как написано в статье, добавил на дев версию сайта в папку **.git/hooks/** [файл](https://github.com/popstas/server-scripts/blob/master/bin/git-hook-post-receive) перейменовал его на **post-receive** (тоесть файл находиться за адресом _сайт/.git/hooks/post-receive_ и сделал его исполняемым **chmod +x .git/hooks/post-receive**

В коммите пишу **исправил ошибки по задаче https://проект.planfix.ru/task/номер_задачи** (проект и номер задачи пишем свой) и в итоги ничего не происходит. Подскажите что я делаю не так?

**Comment by popstas** [comment]
Здравствуйте. Хук post-receive срабатывает в репозитории, куда приходит push.
В нашей схеме хук стоит на боевом сайте, куда разработчик пушит изменения.

Скорее всего, вам надо прописать хук на прод репозитории.
Если не поможет, проверьте, срабатывает ли вообще хук, допишите в начало что-то вроде:
```
echo "post-receive called" >> ~/post-receive.log
```

Кстати, в статье этого нет: мы недавно добавили в этот хук автоматическую простановку выбаботки в планфикс через аналитики (тайм-трекинг, для отчетов в планфиксе), если интересно, могу описать.

**Comment by andruwa13** [comment]
@popstas  что-то не хочет запускаться хук (как-то странно, в логах не записывается). А ваш скрипт реально настроить для вебхука?

**Comment by popstas** [comment]
Как успехи?

Вебхук просто отправляет POST-запрос на заданный урл, так что для этого нужно создавать серверную часть, чего делать не хочется. В таком случае

Мне стало интересно, как подключить мой хук к Gitlab, поделюсь результатами.  
Сразу скажу, что я искал способ добавить именно глобальный хук, сразу для всех проектов.

Проверял на Gitlab 8.16.6, развернут на своем сервере в Docker - https://github.com/sameersbn/docker-gitlab

Документация - https://docs.gitlab.com/ce/administration/custom_hooks.html . 
Понял, что надо добавить в hooks папку post-receive.d, в нее положить свой хук, сделать исполняемым.

Я зашел в проект в папке repositories и посмотрел, что `hooks` - симлинк на `/home/git/gitlab-shell/hooks`. Но доступ у меня туда был только если влезть в контейнер через `docker exec`.

При моем способе установки я не могу указать в настройках папку с хуками. Документация говорит:
```
For Omnibus installations, this can be set in gitlab.rb; 
and in source installations, this can be set in gitlab-shell/config.yml
```
Мне ни один из этих способов не подошел, т.к. я могу редактировать только docker-compose.yml поэтому я пробросил ее в контейнер:
``` yaml
 gitlab:
   volumes:
     - /srv/docker/gitlab/gitlab:/home/git/data:Z
     - /srv/docker/gitlab/gitlab/hooks/post-receive.d:/home/git/gitlab-shell/hooks/post-receive.d:Z
 ```

Пересобрал контейнеры:
```
docker-compose stop
docker-compose up -d
```

Попробовал - папка видится. Проверял так: создал там скрипт test:

``` bash
echo "test" >> testhook
```

После пуша поискал его в контейнере:
```
docker exec -it gitlab_gitlab_1 bash
find / -name testhook
```

Он нашелся в папке проекта, куда я пушил.

Мой хук не сработал. Отладил его через echo в тот же файл, оказалось, что в контейнере нет утилиты `mail`, доставил ее прямо в контейнер:
```
apt-get update && apt-get install mailutils
```
После этого утилита mail появилась, но письма не стали отправляться. На этом я пока остановился.

В любом случае это плохой способ, лучше всего найти способ отправить письмо имеющимся софтом и с настройками smtp, которые указаны в конфиге Gitlab, я поищу способ на неделе, но если у вас Gitlab установлен не в контейнере, вам может быть достаточно положить хук в правильную папку.

**Comment by andruwa13** [comment]
У нас GitLab вообще на их хостинге. Если честно поробовал не получилось, поставил на паузу (на следующей недели буду тестить). По поводу мыла, вы поднимите контейнер с почтой (у нас так работает почта с проектами wordpress через наш docker [образ](https://hub.docker.com/r/techakcent/exim4/))

**Comment by andruwa13** [comment]
подскажите пожалуйста что за файл у вас по адресу `GIT_PLANFIX_USERS_FILE="/usr/local/etc/git_planfix_users.txt"`

**Comment by popstas** [comment]
Это список юзеров планфикса, которые делают коммиты, нужен для того, чтобы аналитика подвязывалась к юзеру, в формате "email	Фамилия Имя" (разделение табами, фамилию от имени отделять пробелом). Можно указывать несколько email для одного юзера, по одному на строку:
```
ivanov@company.ru	Иванов Иван
ivan@company.ru	Иванов Иван
pavel@company.ru	Павлов Павел
```

Когда email в коммите находится в списке, аналитика прикрепляется к соответствующему юзеру.

Формат коммита такой:
```
краткое сообщение

полное описание

time:30
https://company.planfix.ru/task/324666
```

Здесь важна ссылка на задачу и time:30, после обработки хуком в задачу прилетит действие от имени юзера (если email из коммита сопоставлен с юзером в Планфиксе) и будет прикреплена аналитика с кол-вом 30, мы так указываем трудозатраты в минутах.

Чтобы это сработало, со стороны Планфикса нужно создать правило, Управление аккаунтом - Работа с email - Правила обработки для задач
![image](https://cloud.githubusercontent.com/assets/3027126/25633408/6804c2d2-2f90-11e7-8f8d-6b0af46fc57d.png)

В "Вид работы" вставляется то, что указано в переменной `PLANFIX_ANALYTIC_NAME`.

Это все работает и не ломается примерно год, но собрано, как видите, для себя :)
